--  Zone File Writer Module Body
--  Implementation of BIND-format zone file generation

with Ada.Text_IO;
with Ada.Calendar;
with Ada.Calendar.Formatting;
with Ada.Directories;
with Ada.Strings.Unbounded;

package body Zone_Writer is

   use Ada.Text_IO;
   use Ada.Strings.Unbounded;

   --  Generate RFC 1912 format serial: YYYYMMDDnn
   function Increment_Serial (Current : Natural) return Natural is
      use Ada.Calendar;
      use Ada.Calendar.Formatting;

      Now     : constant Time := Clock;
      Year    : constant Year_Number := Ada.Calendar.Formatting.Year (Now);
      Month   : constant Month_Number := Ada.Calendar.Formatting.Month (Now);
      Day     : constant Day_Number := Ada.Calendar.Formatting.Day (Now);

      Date_Part : constant Natural :=
         (Year * 10000) + (Month * 100) + Day;
      Today_Serial : constant Natural := Date_Part * 100;  --  YYYYMMDDnn
   begin
      --  If current serial is from today, increment sequence number
      if Current >= Today_Serial and Current < Today_Serial + 100 then
         return Current + 1;
      else
         --  New day, reset to nn=01
         return Today_Serial + 1;
      end if;
   end Increment_Serial;

   --  Generate SOA record
   function Generate_SOA (Config : Zone_Config) return String is
      Origin_Str : constant String := DNS_Records.Domain_Strings.To_String (Config.Origin);
      NS_Str     : constant String := DNS_Records.Domain_Strings.To_String (Config.Primary_NS);
      HM_Str     : constant String := DNS_Records.Domain_Strings.To_String (Config.Hostmaster);
   begin
      return Origin_Str & ". IN SOA " & NS_Str & ". " & HM_Str & ". (" & ASCII.LF &
             "    " & Natural'Image (Config.Serial) & "  ; Serial" & ASCII.LF &
             "    " & DNS_Records.TTL_Seconds'Image (Config.Refresh) & "  ; Refresh" & ASCII.LF &
             "    " & DNS_Records.TTL_Seconds'Image (Config.Retry) & "  ; Retry" & ASCII.LF &
             "    " & DNS_Records.TTL_Seconds'Image (Config.Expire) & "  ; Expire" & ASCII.LF &
             "    " & DNS_Records.TTL_Seconds'Image (Config.Minimum_TTL) & "  ; Minimum TTL" & ASCII.LF &
             ")";
   end Generate_SOA;

   --  Generate zone file header
   function Generate_Header (Config : Zone_Config) return String is
      Origin_Str : constant String := DNS_Records.Domain_Strings.To_String (Config.Origin);
   begin
      return ";; Zone file for " & Origin_Str & ASCII.LF &
             ";; Generated by HINFO-LOC Fluctuator" & ASCII.LF &
             ";; " & Ada.Calendar.Formatting.Image (Ada.Calendar.Clock) & ASCII.LF &
             ";;" & ASCII.LF &
             "$ORIGIN " & Origin_Str & "." & ASCII.LF &
             "$TTL " & DNS_Records.TTL_Seconds'Image (Config.Minimum_TTL) & ASCII.LF &
             ASCII.LF;
   end Generate_Header;

   --  Convert resource record to zone file format
   function To_Zone_Format (RR : DNS_Records.Resource_Record) return String is
      Domain_Str : constant String := DNS_Records.Domain_Strings.To_String (RR.Domain);
   begin
      case RR.RR_Type is
         when DNS_Records.HINFO_Type =>
            declare
               CPU_Str : constant String :=
                  DNS_Records.CPU_Strings.To_String (RR.HINFO.CPU);
               OS_Str  : constant String :=
                  DNS_Records.OS_Strings.To_String (RR.HINFO.OS);
            begin
               return Domain_Str & ". " &
                      DNS_Records.TTL_Seconds'Image (RR.HINFO.TTL) & " " &
                      DNS_Records.To_String (RR.HINFO.Class) & " HINFO " &
                      """" & CPU_Str & """ """ & OS_Str & """";
            end;

         when DNS_Records.LOC_Type =>
            --  RFC 1876 format: lat lon alt size h_prec v_prec
            declare
               Lat : constant DNS_Records.Latitude_Degrees := RR.LOC.Latitude;
               Lon : constant DNS_Records.Longitude_Degrees := RR.LOC.Longitude;
               Alt : constant DNS_Records.Altitude_Meters := RR.LOC.Altitude;

               --  Convert to degrees/minutes/seconds format
               Lat_Deg : constant Integer := Integer (abs Float (Lat));
               Lat_Min : constant Integer := Integer ((abs Float (Lat) - Float (Lat_Deg)) * 60.0);
               Lat_Sec : constant Float := ((abs Float (Lat) - Float (Lat_Deg)) * 60.0 - Float (Lat_Min)) * 60.0;
               Lat_Dir : constant Character := (if Lat >= 0.0 then 'N' else 'S');

               Lon_Deg : constant Integer := Integer (abs Float (Lon));
               Lon_Min : constant Integer := Integer ((abs Float (Lon) - Float (Lon_Deg)) * 60.0);
               Lon_Sec : constant Float := ((abs Float (Lon) - Float (Lon_Deg)) * 60.0 - Float (Lon_Min)) * 60.0;
               Lon_Dir : constant Character := (if Lon >= 0.0 then 'E' else 'W');
            begin
               return Domain_Str & ". " &
                      DNS_Records.TTL_Seconds'Image (RR.LOC.TTL) & " " &
                      DNS_Records.To_String (RR.LOC.Class) & " LOC " &
                      Integer'Image (Lat_Deg) & " " &
                      Integer'Image (Lat_Min) & " " &
                      Float'Image (Lat_Sec) & " " &
                      Lat_Dir & " " &
                      Integer'Image (Lon_Deg) & " " &
                      Integer'Image (Lon_Min) & " " &
                      Float'Image (Lon_Sec) & " " &
                      Lon_Dir & " " &
                      DNS_Records.Altitude_Meters'Image (Alt) & "m " &
                      DNS_Records.Size_Centimeters'Image (RR.LOC.Size / 100) & "m " &
                      DNS_Records.Size_Centimeters'Image (RR.LOC.Horizontal_Prec / 100) & "m " &
                      DNS_Records.Size_Centimeters'Image (RR.LOC.Vertical_Prec / 100) & "m";
            end;
      end case;
   end To_Zone_Format;

   --  Atomic file write (write to temp, then rename)
   procedure Atomic_Write_File (
      Filename : String;
      Content  : String
   ) is
      Temp_File : constant String := Filename & ".tmp";
      File      : File_Type;
   begin
      --  Write to temporary file
      Create (File, Out_File, Temp_File);
      Put (File, Content);
      Close (File);

      --  Atomic rename (on POSIX systems)
      Ada.Directories.Rename (Temp_File, Filename);

   exception
      when others =>
         if Is_Open (File) then
            Close (File);
         end if;
         --  Clean up temp file if it exists
         if Ada.Directories.Exists (Temp_File) then
            Ada.Directories.Delete_File (Temp_File);
         end if;
         raise;
   end Atomic_Write_File;

   --  Write complete zone file
   procedure Write_Zone_File (
      Filename : String;
      Config   : Zone_Config;
      Records  : RR_Vectors.Vector
   ) is
      Content : Unbounded_String;
   begin
      --  Build zone file content
      Content := To_Unbounded_String (Generate_Header (Config));

      --  Add SOA record
      Append (Content, Generate_SOA (Config) & ASCII.LF & ASCII.LF);

      --  Add NS record (basic)
      Append (Content, "@  IN  NS  " &
              DNS_Records.Domain_Strings.To_String (Config.Primary_NS) &
              "." & ASCII.LF & ASCII.LF);

      --  Add resource records
      Append (Content, ";; Resource Records" & ASCII.LF);
      for RR of Records loop
         Append (Content, To_Zone_Format (RR) & ASCII.LF);
      end loop;

      --  Atomic write
      Atomic_Write_File (Filename, To_String (Content));
   end Write_Zone_File;

   --  Append records to existing zone file
   procedure Append_To_Zone_File (
      Filename : String;
      Records  : RR_Vectors.Vector
   ) is
      File : File_Type;
   begin
      --  Open for append
      Open (File, Append_File, Filename);

      --  Add timestamp comment
      Put_Line (File, "");
      Put_Line (File, ";; Appended " &
                Ada.Calendar.Formatting.Image (Ada.Calendar.Clock));

      --  Add records
      for RR of Records loop
         Put_Line (File, To_Zone_Format (RR));
      end loop;

      Close (File);

   exception
      when Name_Error =>
         raise;  --  File doesn't exist
      when others =>
         if Is_Open (File) then
            Close (File);
         end if;
         raise;
   end Append_To_Zone_File;

end Zone_Writer;
